// ── BlogBriefOutput ───────────────────────────────────────────────────────────
// Renders the structured blog brief as named sections.
// Each section has a copy button. Export bar at top.

import React, { useState } from 'react';

// ── Tiny copy button ──────────────────────────────────────────────────────────
function CopyBtn({ text, label = 'Copy' }) {
  const [copied, setCopied] = useState(false);
  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    });
  }
  return (
    <button className="bb-copy-btn" onClick={handleCopy} title="Copy to clipboard">
      {copied ? '✓ Copied' : `⎘ ${label}`}
    </button>
  );
}

// ── Section wrapper ───────────────────────────────────────────────────────────
function BriefSection({ icon, title, badge, copyText, children }) {
  return (
    <div className="bb-section">
      <div className="bb-section-header">
        <div className="bb-section-title">
          <span className="bb-section-icon">{icon}</span>
          {title}
          {badge && <span className={`bb-section-badge ${badge.type}`}>{badge.label}</span>}
        </div>
        {copyText && <CopyBtn text={copyText} />}
      </div>
      <div className="bb-section-body">{children}</div>
    </div>
  );
}

// ── Pill badge ────────────────────────────────────────────────────────────────
function Pill({ label, type = 'default' }) {
  return <span className={`bb-pill bb-pill--${type}`}>{label}</span>;
}

// ── Priority label ────────────────────────────────────────────────────────────
function Priority({ value }) {
  const map = {
    'must-include':    { label: 'Must',   type: 'red' },
    'should-include':  { label: 'Should', type: 'yellow' },
    'nice-to-have':    { label: 'Nice',   type: 'green' },
  };
  const p = map[value] || { label: value, type: 'default' };
  return <span className={`bb-priority bb-priority--${p.type}`}>{p.label}</span>;
}

// ── Main output component ─────────────────────────────────────────────────────
export default function BlogBriefOutput({ brief, url, keyword }) {

  // Build full plain-text export
  function buildExportText() {
    const lines = [
      `BLOG BRIEF — Generated by PageIQ`,
      `URL: ${url}`,
      `Target Keyword: ${brief.targetKeyword}`,
      `Generated: ${new Date().toLocaleDateString()}`,
      '',
      '═══════════════════════════════',
      'OVERVIEW',
      '═══════════════════════════════',
      `Search Intent: ${brief.searchIntent}`,
      `Intent Explanation: ${brief.intentExplanation}`,
      `Recommended Length: ${brief.recommendedLength?.ideal || '—'} words (${brief.recommendedLength?.min}–${brief.recommendedLength?.max})`,
      `Rationale: ${brief.recommendedLength?.rationale || ''}`,
      `Secondary Keywords: ${brief.secondaryKeywords?.join(', ')}`,
      '',
      '═══════════════════════════════',
      'TITLE OPTIONS',
      '═══════════════════════════════',
      ...(brief.titleOptions || []).map((t, i) => `${i + 1}. ${t.title}\n   Angle: ${t.angle} | Emotion: ${t.emotion}`),
      '',
      '═══════════════════════════════',
      'H1 / OUTLINE',
      '═══════════════════════════════',
      `H1: ${brief.outline?.h1}`,
      `Intro: ${brief.outline?.intro}`,
      '',
      ...(brief.outline?.sections || []).flatMap(s => [
        `H2: ${s.h2}  (~${s.wordCount} words)`,
        `  Purpose: ${s.purpose}`,
        ...(s.h3s || []).map(h => `  H3: ${h}`),
        `  Notes: ${s.writingNotes || ''}`,
        '',
      ]),
      `Conclusion: ${brief.outline?.conclusion}`,
      '',
      '═══════════════════════════════',
      'FAQ SECTION',
      '═══════════════════════════════',
      ...(brief.faqSection || []).map(f => `Q: ${f.question}\nA hint: ${f.answerHint}\n`),
      '═══════════════════════════════',
      'ENTITY COVERAGE',
      '═══════════════════════════════',
      ...(brief.entityCoverage || []).map(e => `[${e.priority}] ${e.entity} (${e.type}) — ${e.context}`),
      '',
      '═══════════════════════════════',
      'INTERNAL LINKS',
      '═══════════════════════════════',
      ...(brief.internalLinks || []).map(l => `"${l.anchorText}" → ${l.targetPageType} (${l.placement})\n  Why: ${l.reason}`),
      '',
      '═══════════════════════════════',
      'CTA IDEAS',
      '═══════════════════════════════',
      ...(brief.ctaIdeas || []).map(c => `[${c.placement}] "${c.cta}" — ${c.goal} | style: ${c.style}`),
      '',
      '═══════════════════════════════',
      'TONE & VOICE',
      '═══════════════════════════════',
      `Recommended: ${brief.toneAndVoice?.recommended}`,
      `Avoid: ${brief.toneAndVoice?.avoid}`,
      `Examples: ${(brief.toneAndVoice?.examples || []).join(' / ')}`,
      '',
      '═══════════════════════════════',
      'COMPETITOR ANGLE',
      '═══════════════════════════════',
      brief.competitorAngle || '',
      '',
      '── Ahrefs enrichment (pending) ──',
      `Keyword Volume: ${brief.ahrefs?.keywordVolume ?? 'Not yet enriched'}`,
      `Keyword Difficulty: ${brief.ahrefs?.keywordDifficulty ?? 'Not yet enriched'}`,
      `Competitor URLs: ${brief.ahrefs?.competitorUrls?.length ? brief.ahrefs.competitorUrls.join(', ') : 'Not yet enriched'}`,
    ];
    return lines.join('\n');
  }

  const intentColors = {
    informational: 'blue',
    transactional:  'green',
    commercial:     'purple',
    navigational:   'gray',
  };

  return (
    <div className="bb-output">

      {/* ── Export bar ── */}
      <div className="bb-export-bar">
        <div className="bb-export-label">
          <span className="bb-export-kw">✍️ {brief.targetKeyword}</span>
          <Pill label={brief.searchIntent} type={intentColors[brief.searchIntent] || 'blue'} />
          <span className="bb-export-length">~{brief.recommendedLength?.ideal} words</span>
        </div>
        <div className="bb-export-actions">
          <CopyBtn text={buildExportText()} label="Copy All" />
          <button
            className="bb-btn-download"
            onClick={() => {
              const blob = new Blob([buildExportText()], { type: 'text/plain' });
              const a = document.createElement('a');
              a.href = URL.createObjectURL(blob);
              a.download = `pageiq-brief-${brief.targetKeyword.replace(/\s+/g, '-')}.txt`;
              a.click();
            }}
          >
            ↓ Download .txt
          </button>
        </div>
      </div>

      {/* ── Overview strip ── */}
      <div className="bb-overview-strip">
        <div className="bb-overview-item">
          <div className="bb-overview-label">Intent</div>
          <div className="bb-overview-value"><Pill label={brief.searchIntent} type={intentColors[brief.searchIntent] || 'blue'} /></div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Length</div>
          <div className="bb-overview-value">{brief.recommendedLength?.min}–{brief.recommendedLength?.max} words</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Sections</div>
          <div className="bb-overview-value">{brief.outline?.sections?.length || 0} H2s</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">FAQs</div>
          <div className="bb-overview-value">{brief.faqSection?.length || 0} questions</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Entities</div>
          <div className="bb-overview-value">{brief.entityCoverage?.length || 0} to cover</div>
        </div>
        <div className="bb-overview-item bb-overview-item--future">
          <div className="bb-overview-label">KW Volume</div>
          <div className="bb-overview-value bb-future-pill">Ahrefs ⌛</div>
        </div>
        <div className="bb-overview-item bb-overview-item--future">
          <div className="bb-overview-label">KW Difficulty</div>
          <div className="bb-overview-value bb-future-pill">Ahrefs ⌛</div>
        </div>
      </div>

      <p className="bb-intent-explanation">{brief.intentExplanation}</p>

      {/* ── Keyword ── */}
      <BriefSection icon="🎯" title="Target Keyword"
        copyText={[brief.targetKeyword, ...(brief.secondaryKeywords || [])].join('\n')}>
        <div className="bb-kw-primary">{brief.targetKeyword}</div>
        <div className="bb-kw-secondary-label">Secondary keywords</div>
        <div className="bb-chips-row">
          {(brief.secondaryKeywords || []).map(kw => (
            <span key={kw} className="bb-chip">{kw}</span>
          ))}
        </div>
      </BriefSection>

      {/* ── Title Options ── */}
      <BriefSection icon="📰" title="Title Options"
        copyText={(brief.titleOptions || []).map((t, i) => `${i+1}. ${t.title}`).join('\n')}>
        <div className="bb-titles-list">
          {(brief.titleOptions || []).map((t, i) => (
            <div key={i} className="bb-title-item">
              <div className="bb-title-num">{i + 1}</div>
              <div className="bb-title-body">
                <div className="bb-title-text">{t.title}</div>
                <div className="bb-title-meta">
                  <span className="bb-title-angle">{t.angle}</span>
                  <span className={`bb-emotion bb-emotion--${t.emotion}`}>{t.emotion}</span>
                </div>
              </div>
              <CopyBtn text={t.title} label="" />
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Outline ── */}
      <BriefSection icon="📋" title="Article Outline"
        copyText={[
          `H1: ${brief.outline?.h1}`,
          `Intro: ${brief.outline?.intro}`,
          ...(brief.outline?.sections || []).flatMap(s => [
            `\nH2: ${s.h2}`,
            ...(s.h3s || []).map(h => `  H3: ${h}`),
          ]),
          `\nConclusion: ${brief.outline?.conclusion}`,
        ].join('\n')}>
        <div className="bb-outline">
          <div className="bb-outline-h1">
            <span className="bb-hx-tag">H1</span>
            <span className="bb-hx-text">{brief.outline?.h1}</span>
          </div>
          <div className="bb-outline-intro">{brief.outline?.intro}</div>

          {(brief.outline?.sections || []).map((s, i) => (
            <div key={i} className="bb-outline-section">
              <div className="bb-outline-h2">
                <span className="bb-hx-tag">H2</span>
                <span className="bb-hx-text">{s.h2}</span>
                <span className="bb-section-wc">~{s.wordCount}w</span>
              </div>
              <div className="bb-outline-purpose">{s.purpose}</div>
              {(s.h3s || []).map((h3, j) => (
                <div key={j} className="bb-outline-h3">
                  <span className="bb-hx-tag bb-hx-tag--h3">H3</span>
                  <span className="bb-hx-text">{h3}</span>
                </div>
              ))}
              {s.writingNotes && (
                <div className="bb-writing-note">✏️ {s.writingNotes}</div>
              )}
            </div>
          ))}

          <div className="bb-outline-conclusion">
            <span className="bb-hx-tag">END</span>
            <span className="bb-hx-text">{brief.outline?.conclusion}</span>
          </div>
        </div>
      </BriefSection>

      {/* ── FAQ ── */}
      <BriefSection icon="❓" title="FAQ Section"
        copyText={(brief.faqSection || []).map(f => `Q: ${f.question}\nA: ${f.answerHint}`).join('\n\n')}>
        <div className="bb-faq-list">
          {(brief.faqSection || []).map((f, i) => (
            <div key={i} className="bb-faq-item">
              <div className="bb-faq-q">{f.question}</div>
              <div className="bb-faq-hint">{f.answerHint}</div>
              <span className="bb-faq-source">source: {f.source}</span>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Entity Coverage ── */}
      <BriefSection icon="🏷️" title="Entity Coverage"
        copyText={(brief.entityCoverage || []).map(e => `[${e.priority}] ${e.entity} (${e.type}): ${e.context}`).join('\n')}>
        <div className="bb-entity-list">
          {(brief.entityCoverage || []).map((e, i) => (
            <div key={i} className="bb-entity-item">
              <Priority value={e.priority} />
              <div className="bb-entity-body">
                <span className="bb-entity-name">{e.entity}</span>
                <span className="bb-entity-type">{e.type}</span>
              </div>
              <div className="bb-entity-context">{e.context}</div>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Internal Links ── */}
      <BriefSection icon="🔗" title="Internal Link Suggestions"
        copyText={(brief.internalLinks || []).map(l => `"${l.anchorText}" → ${l.targetPageType} (${l.placement}): ${l.reason}`).join('\n')}>
        <div className="bb-links-list">
          {(brief.internalLinks || []).map((l, i) => (
            <div key={i} className="bb-link-item">
              <div className="bb-link-anchor">"{l.anchorText}"</div>
              <div className="bb-link-meta">
                <span className="bb-link-target">→ {l.targetPageType}</span>
                <span className="bb-link-placement">{l.placement}</span>
              </div>
              <div className="bb-link-reason">{l.reason}</div>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── CTAs ── */}
      <BriefSection icon="⚡" title="CTA Ideas"
        copyText={(brief.ctaIdeas || []).map(c => `[${c.placement}] "${c.cta}" — ${c.goal}`).join('\n')}>
        <div className="bb-cta-list">
          {(brief.ctaIdeas || []).map((c, i) => (
            <div key={i} className="bb-cta-item">
              <div className="bb-cta-text">"{c.cta}"</div>
              <div className="bb-cta-meta">
                <span className="bb-cta-placement">{c.placement}</span>
                <span className="bb-cta-style">{c.style}</span>
                <span className="bb-cta-goal">{c.goal}</span>
              </div>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Tone & Voice ── */}
      <BriefSection icon="🎙️" title="Tone & Voice">
        <div className="bb-tone-grid">
          <div className="bb-tone-item">
            <div className="bb-tone-label">Recommended tone</div>
            <div className="bb-tone-value">{brief.toneAndVoice?.recommended}</div>
          </div>
          <div className="bb-tone-item">
            <div className="bb-tone-label">Avoid</div>
            <div className="bb-tone-value">{brief.toneAndVoice?.avoid}</div>
          </div>
        </div>
        {(brief.toneAndVoice?.examples || []).length > 0 && (
          <div className="bb-tone-examples">
            <div className="bb-tone-label">Example phrasing</div>
            {brief.toneAndVoice.examples.map((ex, i) => (
              <div key={i} className="bb-tone-example">"{ex}"</div>
            ))}
          </div>
        )}
      </BriefSection>

      {/* ── Competitor Angle ── */}
      <BriefSection icon="🏆" title="Competitor Differentiation"
        copyText={brief.competitorAngle}>
        <p className="bb-competitor-text">{brief.competitorAngle}</p>
      </BriefSection>

      {/* ── Ahrefs placeholder ── */}
      <div className="bb-ahrefs-stub">
        <div className="bb-ahrefs-header">
          <span className="bb-ahrefs-icon">📊</span>
          <span className="bb-ahrefs-title">Ahrefs Enrichment</span>
          <span className="bb-ahrefs-badge">Coming Soon</span>
        </div>
        <div className="bb-ahrefs-grid">
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Monthly Search Volume</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Keyword Difficulty</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Top Competitor URLs</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
        </div>
        <p className="bb-ahrefs-note">
          Connect your Ahrefs account to automatically enrich keyword volume, difficulty, and competitor analysis.
        </p>
      </div>

    </div>
  );
}
