// ── BlogBriefOutput ───────────────────────────────────────────────────────────
// Renders the structured blog brief as named sections.
// Matches the lean JSON schema from generate-brief.js

import React, { useState } from 'react';
import WriteArticleButton from './WriteArticleButton';

// ── Tiny copy button ──────────────────────────────────────────────────────────
function CopyBtn({ text, label = 'Copy' }) {
  const [copied, setCopied] = useState(false);
  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    });
  }
  return (
    <button className="bb-copy-btn" onClick={handleCopy} title="Copy to clipboard">
      {copied ? '✓ Copied' : `⎘ ${label}`}
    </button>
  );
}

// ── Section wrapper ───────────────────────────────────────────────────────────
function BriefSection({ icon, title, copyText, children }) {
  return (
    <div className="bb-section">
      <div className="bb-section-header">
        <div className="bb-section-title">
          <span className="bb-section-icon">{icon}</span>
          {title}
        </div>
        {copyText && <CopyBtn text={copyText} />}
      </div>
      <div className="bb-section-body">{children}</div>
    </div>
  );
}

// ── Pill badge ────────────────────────────────────────────────────────────────
function Pill({ label, type = 'default' }) {
  return <span className={`bb-pill bb-pill--${type}`}>{label}</span>;
}

// ── Main output component ─────────────────────────────────────────────────────
export default function BlogBriefOutput({ brief, url, keyword }) {

  // Build full plain-text export
  function buildExportText() {
    const lines = [
      `BLOG BRIEF — Generated by PageIQ`,
      `URL: ${url}`,
      `Target Keyword: ${brief.targetKeyword}`,
      `Generated: ${new Date().toLocaleDateString()}`,
      '',
      '═══════════════════════════════',
      'OVERVIEW',
      '═══════════════════════════════',
      `Search Intent: ${brief.searchIntent}`,
      `Recommended Word Count: ${brief.recommendedWordCount} words`,
      `Secondary Keywords: ${(brief.secondaryKeywords || []).join(', ')}`,
      '',
      '═══════════════════════════════',
      'TITLE OPTIONS',
      '═══════════════════════════════',
      ...(brief.titles || []).map((t, i) => `${i + 1}. ${t}`),
      '',
      '═══════════════════════════════',
      'H1 / OUTLINE',
      '═══════════════════════════════',
      `H1: ${brief.outline?.h1}`,
      `Intro: ${brief.outline?.intro}`,
      '',
      ...(brief.outline?.h2s || []).flatMap(s => [
        `H2: ${s.heading}`,
        `  Note: ${s.note}`,
        '',
      ]),
      `Conclusion: ${brief.outline?.conclusion}`,
      '',
      '═══════════════════════════════',
      'FAQ SECTION',
      '═══════════════════════════════',
      ...(brief.faqs || []).map(f => `Q: ${f.q}\nHint: ${f.hint}\n`),
      '═══════════════════════════════',
      'MUST-INCLUDE ENTITIES',
      '═══════════════════════════════',
      (brief.mustIncludeEntities || []).join(', '),
      '',
      '═══════════════════════════════',
      'INTERNAL LINKS',
      '═══════════════════════════════',
      ...(brief.internalLinks || []).map(l => `"${l.anchor}" → ${l.page}`),
      '',
      '═══════════════════════════════',
      'CTA',
      '═══════════════════════════════',
      brief.cta || '',
      '',
      '═══════════════════════════════',
      'TONE & DIFFERENTIATOR',
      '═══════════════════════════════',
      `Tone: ${brief.tone}`,
      `Differentiator: ${brief.differentiator}`,
    ];
    return lines.join('\n');
  }

  const intentColors = {
    informational: 'blue',
    transactional:  'green',
    commercial:     'purple',
    navigational:   'gray',
  };

  return (
    <div className="bb-output">

      {/* ── Export bar ── */}
      <div className="bb-export-bar">
        <div className="bb-export-label">
          <span className="bb-export-kw">✍️ {brief.targetKeyword}</span>
          <Pill label={brief.searchIntent} type={intentColors[brief.searchIntent] || 'blue'} />
          <span className="bb-export-length">~{brief.recommendedWordCount} words</span>
        </div>
        <div className="bb-export-actions">
          <WriteArticleButton brief={brief} url={url} />
          <CopyBtn text={buildExportText()} label="Copy All" />
          <button
            className="bb-btn-download"
            onClick={() => {
              const blob = new Blob([buildExportText()], { type: 'text/plain' });
              const a = document.createElement('a');
              a.href = URL.createObjectURL(blob);
              a.download = `pageiq-brief-${(brief.targetKeyword || 'brief').replace(/\s+/g, '-')}.txt`;
              a.click();
            }}
          >
            ↓ Download .txt
          </button>
        </div>
      </div>

      {/* ── Overview strip ── */}
      <div className="bb-overview-strip">
        <div className="bb-overview-item">
          <div className="bb-overview-label">Intent</div>
          <div className="bb-overview-value"><Pill label={brief.searchIntent} type={intentColors[brief.searchIntent] || 'blue'} /></div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Length</div>
          <div className="bb-overview-value">{brief.recommendedWordCount ? `~${brief.recommendedWordCount}` : '—'} words</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Sections</div>
          <div className="bb-overview-value">{brief.outline?.h2s?.length || 0} H2s</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">FAQs</div>
          <div className="bb-overview-value">{brief.faqs?.length || 0} questions</div>
        </div>
        <div className="bb-overview-item">
          <div className="bb-overview-label">Entities</div>
          <div className="bb-overview-value">{brief.mustIncludeEntities?.length || 0} to cover</div>
        </div>
        <div className="bb-overview-item bb-overview-item--future">
          <div className="bb-overview-label">KW Volume</div>
          <div className="bb-overview-value bb-future-pill">Ahrefs ⌛</div>
        </div>
        <div className="bb-overview-item bb-overview-item--future">
          <div className="bb-overview-label">KW Difficulty</div>
          <div className="bb-overview-value bb-future-pill">Ahrefs ⌛</div>
        </div>
      </div>

      {/* ── Keyword ── */}
      <BriefSection icon="🎯" title="Target Keyword"
        copyText={[brief.targetKeyword, ...(brief.secondaryKeywords || [])].join('\n')}>
        <div className="bb-kw-primary">{brief.targetKeyword}</div>
        <div className="bb-kw-secondary-label">Secondary keywords</div>
        <div className="bb-chips-row">
          {(brief.secondaryKeywords || []).map(kw => (
            <span key={kw} className="bb-chip">{kw}</span>
          ))}
        </div>
      </BriefSection>

      {/* ── Title Options ── */}
      <BriefSection icon="📰" title="Title Options"
        copyText={(brief.titles || []).map((t, i) => `${i+1}. ${t}`).join('\n')}>
        <div className="bb-titles-list">
          {(brief.titles || []).map((t, i) => (
            <div key={i} className="bb-title-item">
              <div className="bb-title-num">{i + 1}</div>
              <div className="bb-title-body">
                <div className="bb-title-text">{t}</div>
              </div>
              <CopyBtn text={t} label="" />
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Outline ── */}
      <BriefSection icon="📋" title="Article Outline"
        copyText={[
          `H1: ${brief.outline?.h1}`,
          `Intro: ${brief.outline?.intro}`,
          ...(brief.outline?.h2s || []).map(s => `\nH2: ${s.heading}\n  Note: ${s.note}`),
          `\nConclusion: ${brief.outline?.conclusion}`,
        ].join('\n')}>
        <div className="bb-outline">
          <div className="bb-outline-h1">
            <span className="bb-hx-tag">H1</span>
            <span className="bb-hx-text">{brief.outline?.h1}</span>
          </div>
          <div className="bb-outline-intro">{brief.outline?.intro}</div>

          {(brief.outline?.h2s || []).map((s, i) => (
            <div key={i} className="bb-outline-section">
              <div className="bb-outline-h2">
                <span className="bb-hx-tag">H2</span>
                <span className="bb-hx-text">{s.heading}</span>
              </div>
              {s.note && <div className="bb-writing-note">✏️ {s.note}</div>}
            </div>
          ))}

          <div className="bb-outline-conclusion">
            <span className="bb-hx-tag">END</span>
            <span className="bb-hx-text">{brief.outline?.conclusion}</span>
          </div>
        </div>
      </BriefSection>

      {/* ── FAQ ── */}
      <BriefSection icon="❓" title="FAQ Section"
        copyText={(brief.faqs || []).map(f => `Q: ${f.q}\nA: ${f.hint}`).join('\n\n')}>
        <div className="bb-faq-list">
          {(brief.faqs || []).map((f, i) => (
            <div key={i} className="bb-faq-item">
              <div className="bb-faq-q">{f.q}</div>
              <div className="bb-faq-hint">{f.hint}</div>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── Entity Coverage ── */}
      <BriefSection icon="🏷️" title="Entity Coverage"
        copyText={(brief.mustIncludeEntities || []).join(', ')}>
        <div className="bb-chips-row" style={{ flexWrap: 'wrap', gap: '8px' }}>
          {(brief.mustIncludeEntities || []).map((e, i) => (
            <span key={i} className="bb-chip">✓ {e}</span>
          ))}
        </div>
      </BriefSection>

      {/* ── Internal Links ── */}
      <BriefSection icon="🔗" title="Internal Link Suggestions"
        copyText={(brief.internalLinks || []).map(l => `"${l.anchor}" → ${l.page}`).join('\n')}>
        <div className="bb-links-list">
          {(brief.internalLinks || []).map((l, i) => (
            <div key={i} className="bb-link-item">
              <div className="bb-link-anchor">"{l.anchor}"</div>
              <div className="bb-link-meta">
                <span className="bb-link-target">→ {l.page}</span>
              </div>
            </div>
          ))}
        </div>
      </BriefSection>

      {/* ── CTA ── */}
      <BriefSection icon="⚡" title="CTA Suggestion" copyText={brief.cta}>
        <div className="bb-competitor-text" style={{ fontSize: '1rem', fontWeight: 500 }}>
          "{brief.cta}"
        </div>
      </BriefSection>

      {/* ── Tone & Voice ── */}
      <BriefSection icon="🎙️" title="Tone & Voice">
        <div className="bb-tone-grid">
          <div className="bb-tone-item">
            <div className="bb-tone-label">Recommended tone</div>
            <div className="bb-tone-value">{brief.tone}</div>
          </div>
        </div>
      </BriefSection>

      {/* ── Competitor Angle ── */}
      <BriefSection icon="🏆" title="Competitor Differentiation"
        copyText={brief.differentiator}>
        <p className="bb-competitor-text">{brief.differentiator}</p>
      </BriefSection>

      {/* ── Ahrefs placeholder ── */}
      <div className="bb-ahrefs-stub">
        <div className="bb-ahrefs-header">
          <span className="bb-ahrefs-icon">📊</span>
          <span className="bb-ahrefs-title">Ahrefs Enrichment</span>
          <span className="bb-ahrefs-badge">Coming Soon</span>
        </div>
        <div className="bb-ahrefs-grid">
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Monthly Search Volume</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Keyword Difficulty</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
          <div className="bb-ahrefs-item">
            <div className="bb-ahrefs-label">Top Competitor URLs</div>
            <div className="bb-ahrefs-val">—</div>
          </div>
        </div>
        <p className="bb-ahrefs-note">
          Connect your Ahrefs account to automatically enrich keyword volume, difficulty, and competitor analysis.
        </p>
      </div>

    </div>
  );
}
